### ISSUE TITLE
Set the Input value

### ISSUE THREAD

**Issue by nfriacowboy** [mdauner/sveltejs-forms#163]
There no way to set the input value of the Input object.

I will like to bind  the value property of the item and is not possible.

example:

 <Input name="name" label="Name" placeholder="your name" bind:value={user.name}  />

**Comment by nfriacowboy** [comment]
I have a solution for this, how can I share it?

**Comment by mdauner** [comment]
it's now possible to pass attributes. Does this solve your issue? If not then feel free to create a PR with your solution
