### ISSUE TITLE
Input Component extension: define a way to set attributes

### ISSUE THREAD

**Issue by CarloAntenucci** [mdauner/sveltejs-forms#164]
According to issue #120, there's no way to define a class for the input, but not also: there's no way to define any attribute except `name`, `placeholder` or `type`. 
Passing some attributes to the input should be useful to define a custom ID, or if the input is disabled or readonly etc.

Could be possible to define a prop with all attributes we want to pass to the Input in order to customize it?

In addition could also be useful add a slot to override the label for example if we want to add an icon or we want to attach a class.

**Comment by mdauner** [comment]
Thanks for your input. It's possible now to pass attributes. Opened a new issue for overriding the label and in case you like to help feel free to create a PR
