### ISSUE TITLE
Error reported in REPL of your DEMO

### ISSUE THREAD

**Issue by infuzz** [mdauner/sveltejs-forms#169]
**Describe the bug**
In your [DEMO ](https://svelte.dev/repl/8e7deaa261364b4f8b2c0caff1982eeb?version=3.19.2) link, there is an error, so the demo can't work

with  ?version=3.22.3 it works. 

Error reported:
$$restProps is an illegal variable name (Input.svelte:22:36)

**Comment by leejoramo-d51** [comment]
Same issue for me. Changing the version per @infuzz  solves  the problem
